config/routes.rb
Rails.application.routes.draw do
  
  resources :reports do
    collection do
      get 'get_all_reports_user'
    end
  end

  post 'reports/post_report'

  resources :report_types
  resources :report_types
  resources :report_types
  resources :report_types
  resources :report_types
  resources :reports
  
  devise_for :users
  scope "/admin" do
    resources :users
  end

  get 'welcome/index'

  resources :users
  resources :roles
  resources :roles
  resources :users
  resources :roles
  resources :users

  root 'welcome#index'

end

app/controllers/report_types_controller.rb
class ReportTypesController < ApplicationController
  before_action :set_report_type, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  # GET /report_types
  # GET /report_types.json
  def index
    @report_types = ReportType.all
  end

  # GET /report_types/1
  # GET /report_types/1.json
  def show
  end

  # GET /report_types/new
  def new
    @report_type = ReportType.new
  end

  # GET /report_types/1/edit
  def edit
  end

  # POST /report_types
  # POST /report_types.json
  def create
    @report_type = ReportType.new(report_type_params)

    respond_to do |format|
      if @report_type.save
        format.html { redirect_to @report_type, notice: 'Report type was successfully created.' }
        format.json { render :show, status: :created, location: @report_type }
      else
        format.html { render :new }
        format.json { render json: @report_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /report_types/1
  # PATCH/PUT /report_types/1.json
  def update
    respond_to do |format|
      if @report_type.update(report_type_params)
        format.html { redirect_to @report_type, notice: 'Report type was successfully updated.' }
        format.json { render :show, status: :ok, location: @report_type }
      else
        format.html { render :edit }
        format.json { render json: @report_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /report_types/1
  # DELETE /report_types/1.json
  def destroy
    @report_type.destroy
    respond_to do |format|
      format.html { redirect_to report_types_url, notice: 'Report type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report_type
      @report_type = ReportType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def report_type_params
      params.require(:report_type).permit(:description)
    end
end

app/helpers/report_types_helper.rb
module ReportTypesHelper
end

app/views/report_types/_form.html.erb
<%= form_for(report_type) do |f| %>
  <% if report_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(report_type.errors.count, "error") %> prohibited this report_type from being saved:</h2>

      <ul>
      <% report_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field col-sm-12 col-md-6">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <br class="clear">
  <div class="actions row row-centered">
    <%= f.submit :class => "col-xs-12 col-md-3 col-centered" %>
  </div>
<% end %>

app/views/report_types/edit.html.erb
<div class="welcome-body">
  <div class="section">
	    <div class="section-header">
			<h1>Editing Report Type</h1>
		</div>
		<div class="section-content">
			<%= render 'form', report_type: @report_type %>
			<div class="row row-centered">
				<%= link_to 'Ver', @report_type, :class => "btn btn-default col-xs-12 col-md-3 col-centered" %> 
				<%= link_to 'Regresar', report_types_path, :class => "btn btn-default col-xs-12 col-md-3 col-centered" %>
			</div>
			<br class="clear">
		</div>
	</div>
</div>

app/views/report_types/index.html.erb
<div class="welcome-body">
  <div class="section">
    <div class="section-header">
      <h1>Tipos de reporte</h1>
    </div>
    <div class="section-content">
      <table>
        <thead>
          <tr>
                  <th>Descripcion</th>
                  <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @report_types.each do |report_type| %>
            <tr>
              <td><%= report_type.description %></td>
              <td>
                <% if can? :show,report_type %>
                  <%= link_to report_type, :class => "btn btn-info", :title => "Ver" do %>
                    <span class="fa fa-eye"></span>
                  <% end %>
                <% end %>
              </td>
              <td>
                <% if can? :edit,report_type %>
                  <%= link_to edit_report_type_path(report_type), :class => "btn btn-warning", :title => "Editar" do %>
                    <span class="fa fa-pencil"></span>
                  <% end %>
                <% end %>
              </td>
              <td>
                <% if can? :delete,report_type %>
                  <%= link_to report_type, method: :delete, data: { confirm: 'Estas seguro?' }, :class => "btn btn-danger", :title => "Eliminar" do %>
                    <span class="fa fa-trash"></span>
                  <% end %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <br>
      <% if can? :new, ReportType  %>
        <%= link_to new_report_type_path, :class => "btn btn-primary" do %>
          <span class="fa fa-plus"></span> Nuevo tipo de reporte
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/report_types/new.html.erb
<div class="welcome-body">
	<div class="section">
		<div class="section-header">
			<h1>New Report Type</h1>
		</div>
		<div class="section-content">
			<%= render 'form', report_type: @report_type %>
			<div class="row row-centered">
				<%= link_to 'Regresar', report_types_path, :class => "btn btn-default col-xs-12 col-md-3 col-centered" %>
			</div>
		</div>
	</div>
</div>

app/views/report_types/show.html.erb
<div class="welcome-body">
	<div class="section">
		<div class="section-header">
		</div>
		<div class="section-content">
						<p>
			  <strong>Description:</strong>
			  <%= @report_type.description %>
			</p>
						<div class="row row-centered">
				<%= link_to 'Editar', edit_report_type_path(@report_type), :class => "btn btn-default col-xs-12 col-md-3 col-centered" %>
				<%= link_to 'Regresar', report_types_path, :class => "btn btn-default col-xs-12 col-md-3 col-centered" %>
			</div>
		</div>
	</div>
</div>