config/routes.rb
Rails.application.routes.draw do
  
  resources :reports do
    collection do
      get 'get_all_reports_user'
    end
  end

  post 'reports/post_report'

  resources :report_types
  resources :report_types
  resources :report_types
  resources :report_types
  resources :report_types
  resources :reports
  
  devise_for :users
  scope "/admin" do
    resources :users
  end

  get 'welcome/index'

  resources :users
  resources :roles
  resources :roles
  resources :users
  resources :roles
  resources :users

  root 'welcome#index'

end

app/models/role.rb
class Role < ActiveRecord::Base
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_action :set_role, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  # GET /roles
  # GET /roles.json
  def index
    @roles = Role.all
  end

  # GET /roles/1
  # GET /roles/1.json
  def show
  end

  # GET /roles/new
  def new
    @role = Role.new
  end

  # GET /roles/1/edit
  def edit
  end

  # POST /roles
  # POST /roles.json
  def create
    @role = Role.new(role_params)

    respond_to do |format|
      if @role.save
        format.html { redirect_to @role, notice: 'Role was successfully created.' }
        format.json { render :show, status: :created, location: @role }
      else
        format.html { render :new }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /roles/1
  # PATCH/PUT /roles/1.json
  def update
    respond_to do |format|
      if @role.update(role_params)
        format.html { redirect_to @role, notice: 'Role was successfully updated.' }
        format.json { render :show, status: :ok, location: @role }
      else
        format.html { render :edit }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1
  # DELETE /roles/1.json
  def destroy
    @role.destroy
    respond_to do |format|
      format.html { redirect_to roles_url, notice: 'Role was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_role
      @role = Role.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def role_params
      params.require(:role).permit(:name, :description)
    end
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/views/roles/_form.html.erb
<%= form_for(@role) do |f| %>
  <% if @role.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@role.errors.count, "error") %> prohibited this role from being saved:</h2>

      <ul>
      <% @role.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field col-sm-12 col-md-6">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field col-sm-12 col-md-6">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <br class="clear">
  <div class="actions row row-centered">
    <%= f.submit :class => "col-xs-12 col-md-3 col-centered" %>
  </div>
<% end %>

app/views/roles/edit.html.erb
<div class="welcome-body">
	<div class="section">
		<div class="section-header">
			<h1>Editar rol</h1>
		</div>
		<div class="section-content">
			<%= render 'form' %>
			<div class="row row-centered">
				<%= link_to 'Mostrar', @role, :class => "btn btn-default col-xs-12 col-md-3 col-centered" %>
				<%= link_to 'Regresar', roles_path, :class => "btn btn-default col-xs-12 col-md-3 col-centered" %>
			</div>
			<br class="clear">
		</div>
	</div>
</div>

app/views/roles/index.html.erb
<div class="welcome-body">
  <div class="section">
    <div class="section-header">
      <h1>Lista de roles</h1>
    </div>
    <div class="section-content">
      <table>
        <thead>
          <tr>
            <th>Nombre</th>
            <th>Descripcion</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @roles.each do |role| %>
            <tr>
              <td><%= role.name %></td>
              <td><%= role.description %></td>
              <td>
                <%= link_to role, :class => "btn btn-info" do %>
                  <span class="fa fa-eye"></span>
                <% end %>
              </td>
              <td>
                <%= link_to edit_role_path(role), :class => "btn btn-warning" do %>
                  <span class="fa fa-pencil"></span>
                <% end %>
              </td>
              <td>
                <%= link_to role, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger" do %>
                  <span class="fa fa-trash"></span>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <br>

      <%= link_to new_role_path, :class => "btn btn-primary" do %>
        <span class="fa fa-plus"></span> Nuevo rol
      <% end %>
    </div>
  </div>
</div>

app/views/roles/new.html.erb
<div class="welcome-body">
	<div class="section">
		<div class="section-header">
			<h1>Nuevo rol</h1>
		</div>
		<div class="section-content row row-centered">
			<%= render 'form' %>
			<%= link_to 'Back', roles_path, :class => "btn btn-default col-xs-12 col-md-3 col-centered" %>
		</div>
	</div>
</div>

app/views/roles/show.html.erb
<div class="welcome-body">
	<div class="section">
		<div class="section-header">
			<h1>Informacion del rol</h1>
		</div>
		<div class="section-content">
			<div class="row">
				<div class="col-md-6"><h4>Nombre:</h4></div>
				<div class="col-md-6"><h4><%= @role.name %></h4></div>
			</div>
			<div class="row">
				<div class="col-md-6"><h4>Descripcion:</h4></div>
				<div class="col-md-6"><h4><%= @role.description %></h4></div>
			</div>
			<br>
			<div class="row row-centered">
				<%= link_to 'Editar', edit_role_path(@role), :class => "btn btn-default col-xs-12 col-md-3 col-centered" %>
				<%= link_to 'Regresar', roles_path, :class => "btn btn-default col-xs-12 col-md-3 col-centered" %>
			</div>
		</div>
	</div>	
</div>