config/routes.rb
Rails.application.routes.draw do
  
  resources :reports do
    collection do
      get 'get_all_reports_user'
    end
  end

  post 'reports/post_report'

  resources :report_types
  resources :report_types
  resources :report_types
  resources :report_types
  resources :report_types
  resources :reports
  
  devise_for :users
  scope "/admin" do
    resources :users
  end

  get 'welcome/index'

  resources :users
  resources :roles
  resources :roles
  resources :users
  resources :roles
  resources :users

  root 'welcome#index'

end

app/models/report.rb
class Report < ActiveRecord::Base
  belongs_to :user
  belongs_to :report_type
  mount_uploader :avatar, AvatarUploader

  def avatar_url
  	self.avatar.url
  end

  validates :report_type, :avatar, :pos_x, :pos_y, :address, :description, presence: true
end

app/models/report_type.rb
class ReportType < ActiveRecord::Base
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :set_report, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!
  skip_before_filter :authenticate_user!, only: [:post_report, :get_all_reports_user]
  skip_before_action :verify_authenticity_token, only: [:post_report, :get_all_reports_user]

  # GET /reports
  # GET /reports.json
  def index
    if current_user.is_admin?
      @reports = Report.all.order(created_at: :desc)
    elsif current_user.is_jmas?
      @reports = Report.where(:report_type_id => 1).order(created_at: :desc)
    elsif current_user.is_municipio?
      @reports = Report.where(:report_type_id => 2).order(created_at: :desc)
    elsif current_user.is_cfe?
      @reports = Report.where(:report_type_id => 3).order(created_at: :desc)
    end
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
  end

  # GET /reports/new
  def new
    @report = Report.new
  end

  # GET /reports/1/edit
  def edit
  end

  # POST /reports
  # POST /reports.json
  def create
    @report = Report.new(report_params)
    @report.user = current_user
    respond_to do |format|
      if @report.save
        format.html { redirect_to @report, notice: 'Report was successfully created.' }
        format.json { render :show, status: :created, location: @report }
      else
        format.html { render :new }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reports/1
  # PATCH/PUT /reports/1.json
  def update
    respond_to do |format|
      if @report.update(report_params)
        format.html { redirect_to @report, notice: 'Report was successfully updated.' }
        format.json { render :show, status: :ok, location: @report }
      else
        format.html { render :edit }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @report.destroy
    respond_to do |format|
      format.html { redirect_to reports_url, notice: 'Report was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def post_report
    @report = Report.new(report_mobile_params)
    #@report.avatar = params[:avatar]
    if @report.save
      render status: 200, json: {
        message: "El reporte se guardo correctamente.",
        report: @report
      }.to_json
    else
      render status: 500, json: {
        message: "Hubo un error al guardar, intentalo de nuevo mas tarde."
      }.to_json
    end
  end

  def get_all_reports_user
    user_id = params[:user_id]
    @reports = Report.all.where(:user_id => user_id)
    render json: @reports.to_json({:methods => :avatar_url})
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report
      @report = Report.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def report_params
      params.require(:report).permit(:user_id, :report_type_id, :description, :pos_x, :pos_y, :address, :avatar)
    end

    def report_mobile_params
       params.permit(:avatar, :user_id, :report_type_id, :description, :pos_x, :pos_y, :address)
    end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_form.html.erb
<%= form_for(report) do |f| %>
  <% if report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(report.errors.count, "error") %> prohibited this report from being saved:</h2>

      <ul>
      <% report.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field col-sm-6 row-centered">
    <%= image_tag report.avatar.url %>
  </div>
  <div class="field col-sm-6">
    <%= f.label :avatar %><br>
    <%= f.file_field :avatar %>
  </div>
  <div class="field col-sm-12 col-md-6">
    <%= f.label :report_type_id %>
    <%= f.collection_select :report_type_id, ReportType.all, :id, :description  %>
  </div>

  <div class="field col-sm-12 col-md-6">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="field col-sm-12 col-md-6">
    <%= f.label :pos_x %>
    <%= f.text_field :pos_x %>
  </div>

  <div class="field col-sm-12 col-md-6">
    <%= f.label :pos_y %>
    <%= f.text_field :pos_y %>
  </div>

  <div class="field col-sm-12 col-md-6">
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>

  <br class="clear">
  <div class="actions row row-centered">
    <%= f.submit :class => "col-xs-12 col-md-3 col-centered" %>
  </div>
<% end %>

app/views/reports/edit.html.erb
<div class="welcome-body">
  <div class="section">
    <div class="section-header">
		<h1>Editing Report</h1>
	</div>
		<div class="section-content">
			<%= render 'form', report: @report %>
			<div class="row row-centered">
				<%= link_to 'Ver', @report, :class => "btn btn-default col-xs-12 col-md-3 col-centered" %>
				<%= link_to 'Regresar', reports_path, :class => "btn btn-default col-xs-12 col-md-3 col-centered" %>
			</div>
			<br class="clear">
		</div>
	</div>
</div>

app/views/reports/index.html.erb
<div class="welcome-body">
  <div class="section">
    <div class="section-header">
      <h1>Reports</h1>
    </div>
    <div class="section-content">
      <table>
        <thead>
          <tr>
                  <th>User</th>
                  <th>Report type</th>
                  <th>Description</th>
                  <th>Pos x</th>
                  <th>Pos y</th>
                  <th>Address</th>
                  <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @reports.each do |report| %>
            <tr>
                    <td><%= report.user.username %></td>
                    <td><%= report.report_type.description %></td>
                    <td><%= report.description %></td>
                    <td><%= report.pos_x %></td>
                    <td><%= report.pos_y %></td>
                    <td><%= report.address %></td>
                    <td>
                <% if can? :show,report %>
                  <%= link_to report, :class => "btn btn-info", :title => "Ver" do %>
                    <span class="fa fa-eye"></span>
                  <% end %>
                <% end %>
              </td>
              <td>
                <% if can? :edit,report %>
                  <%= link_to edit_report_path(report), :class => "btn btn-warning", :title => "Editar" do %>
                    <span class="fa fa-pencil"></span>
                  <% end %>
                <% end %>
              </td>
              <td>
                <% if can? :delete,report %>
                  <%= link_to report, method: :delete, data: { confirm: 'Estas seguro?' }, :class => "btn btn-danger", :title => "Eliminar" do %>
                    <span class="fa fa-trash"></span>
                  <% end %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <br>
      <% if can? :new, Report  %>
        <%= link_to new_report_path, :class => "btn btn-primary" do %>
          <span class="fa fa-plus"></span> Nuevo report
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/reports/new.html.erb
<div class="welcome-body">
	<div class="section">
		<div class="section-header">
			<h1>New Report</h1>
		</div>
		<div class="section-content">
			<%= render 'form', report: @report %>
			<div class="row row-centered">
				<%= link_to 'Regresar', reports_path, :class => "btn btn-default col-xs-12 col-md-3 col-centered" %>
			</div>
		</div>
	</div>
</div>

app/views/reports/show.html.erb
<div class="welcome-body">
	<div class="section">
		<div class="section-header">
			<h1>Reporte <%= @report.id %></h1>
		</div>
		<div class="section-content">
			<div class="col-md-6">
				<div class="col-md-12">
				  <strong>Usuario:</strong>
				  <%= @report.user.username %>
				</div>
				<div class="col-md-12">
				  <strong>Tipo de reporte:</strong>
				  <%= @report.report_type.description %>
				</div>
				<div class="col-md-12">
				  <strong>Descripcion:</strong>
				  <%= @report.description %>
				</div>
				<div class="col-md-12">
				  <strong>Latitud:</strong>
				  <span id="lat"><%= @report.pos_x %></span>
				</div>
				<div class="col-md-12">
				  <strong>Longitud:</strong>
				  <span id="lng"><%= @report.pos_y %></span>
				</div>
				<div class="col-md-12">
				  <strong>Direccion:</strong>
				  <span id="add"><%= @report.address %></span>
				</div>
			</div>
			<div class="col-md-6">
				<div class="col-md-12" id="map">
				</div>
				<div class="col-md-12 row-centered">
					<%= image_tag @report.avatar.url, :class => "image_report" %>
				</div>
			</div>
			<div class="row row-centered">
				<%= link_to 'Editar', edit_report_path(@report), :class => "btn btn-default col-xs-12 col-md-3 col-centered" %>
				<%= link_to 'Regresar', reports_path, :class => "btn btn-default col-xs-12 col-md-3 col-centered" %>
			</div>
		</div>
	</div>
</div>

<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCHzb6cgjC95Y5VyEkZkSfzDbyK9elslNs&callback=initMap"
async defer></script>

<% content_for :javascript_includes do %>
    <%= javascript_include_tag "google_maps" %>
<% end %>